import { InputField } from "shared/components";

export const RegistrationForm = () => {
  return (
    <form>
      <InputField
        fullWidth
        id="outlined-basic"
        label="Outlined"
        variant="outlined"
      />
      <InputField
        fullWidth
        id="outlined-basic"
        label="Outlined"
        variant="outlined"
      />
      <InputField
        fullWidth
        id="outlined-basic"
        label="Outlined"
        variant="outlined"
      />
      <InputField
        fullWidth
        id="outlined-basic"
        label="Outlined"
        variant="outlined"
      />
      <InputField
        fullWidth
        id="outlined-basic"
        label="Outlined"
        variant="outlined"
      />
      <InputField
        fullWidth
        id="outlined-basic"
        label="Outlined"
        variant="outlined"
      />
      <InputField
        fullWidth
        id="outlined-basic"
        label="Outlined"
        variant="outlined"
      />
    </form>
  );
};
